### ISSUE TITLE
Remove Obsolete Code Related To Regression Test Generation 

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#14]
Commit 96f9df6e08a9f0e6071364560d1499d86d53f831 already removed the package `org.evosuite.regression`. Yet, bits and pieces related to regression test generation still survived. These should be located and cleaned up. For example:
https://github.com/VoglSebastian/evosuite/blob/da567c8c65db84c792a9dc97ab1c846308b037e1/master/src/main/java/org/evosuite/executionmode/TestGeneration.java#L121
and
https://github.com/VoglSebastian/evosuite/blob/da567c8c65db84c792a9dc97ab1c846308b037e1/client/src/main/java/org/evosuite/Properties.java#L1438

**Comment by schweikl** [comment]
I just created draft pull request #28 to address this issue.
Please commit your changes fixing this issue to [`14-remove-obsolete-code-for-regression-test-generation`](https://github.com/VoglSebastian/evosuite/tree/14-remove-obsolete-code-for-regression-test-generation).

**Comment by schweikl** [comment]
How to handle these?
- Should the parameter `isOriginal` be deleted? The JavaDoc says: `@param isOriginal whether or not you want the original or the regression class.`
 https://github.com/VoglSebastian/evosuite/blob/ae735ca5a00d3c7092d12151d9358dbe513077f3/client/src/main/java/org/evosuite/Properties.java#L2303
- https://github.com/VoglSebastian/evosuite/blob/ae735ca5a00d3c7092d12151d9358dbe513077f3/client/src/main/java/org/evosuite/statistics/RuntimeVariable.java#L224
- https://github.com/VoglSebastian/evosuite/blob/ae735ca5a00d3c7092d12151d9358dbe513077f3/client/src/main/java/org/evosuite/statistics/RuntimeVariable.java#L256
- https://github.com/VoglSebastian/evosuite/blob/ae735ca5a00d3c7092d12151d9358dbe513077f3/client/src/main/java/org/evosuite/Properties.java#L1435
- https://github.com/VoglSebastian/evosuite/blob/ae735ca5a00d3c7092d12151d9358dbe513077f3/client/src/main/java/org/evosuite/Properties.java#L2296

Which ones can be safely deleted, which ones must be kept?

**Comment by gofraser** [comment]
This should be done with #28 right?

**Comment by schweikl** [comment]
Yes, now that #28 is merged we can close this issue :+1:
