### ISSUE TITLE
Fix Failing Integration Tests

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#32]
### Context
The following EvoSuite system tests currently fail and should probably be fixed:
- [ ] com.examples.with.different.packagename.testcarver.PersonWithJavaAgentSystemTest.com.examples.with.different.packagename.testcarver.PersonWithJavaAgentSystemTest
- [ ] org.evosuite.assertion.purity.ToStringInspectorSystemTest.testImpureToString
- [ ] org.evosuite.assertion.stable.ArrayDefaultSystemTest.testBooleanDefault
- [ ] org.evosuite.basic.CompositionalFitnessSystemTest.testCompositionalGetFitnessForSeveralFunctions
- [ ] org.evosuite.basic.CompositionalFitnessSystemTest.testGCDExample
- [ ] org.evosuite.basic.SUTDivisionByZeroSystemTest.testDivisionByZero
- [ ] org.evosuite.basic.SUTDivisionByZeroSystemTest.testDivisionByZero
- [ ] org.evosuite.basic.SUTPrintingThatShouldBeMutedSystemTest.testBase
- [ ] org.evosuite.basic.SUTPrintingThatShouldBeMutedSystemTest.testBase
- [ ] org.evosuite.basic.SUTPrintingThatShouldBeMutedSystemTest.testStatic
- [ ] org.evosuite.basic.SUTPrintingThatShouldBeMutedSystemTest.testStatic
- [ ] org.evosuite.basic.TargetMethodPrefixSystemTest.testTargetMethodPrefix1
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithBranchCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithCBranchCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithExceptionCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithIBranchCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithInputCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithLineCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithMethodCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithMethodNoExceptionCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithMethodTraceCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithOnlyLineCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithOutputCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithStrongMutationCoverage
- [ ] org.evosuite.basic.TargetMethodSystemTest.testTargetMethodWithWeakMutationCoverage
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testCatchWithUnknownThrow
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testCheckedExceptionBranchesOneThrow
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testCheckedExceptionBranchesTwoThrows
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testReThrownCheckedAndErrorBranches
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testReThrownCheckedAndUncheckedExceptionBranchesTwoThrows
- [ ] org.evosuite.coverage.exception.ExceptionInstrumentationSystemTest.testReThrownCheckedExceptionBranchesTwoThrows
- [ ] org.evosuite.coverage.ibranch.IBranchSystemTest.testArchiveIBranchAsSecondaryObjective
- [ ] org.evosuite.coverage.ibranch.IBranchSystemTest.testIBranch
- [ ] org.evosuite.coverage.line.LineCoverageFitnessFunctionSystemTest.testLineCoverageFitnessBranchGuidance2WithoutArchive
- [ ] org.evosuite.coverage.line.LineCoverageFitnessFunctionSystemTest.testLineCoverageFitnessBranchGuidanceWithoutArchive
- [ ] org.evosuite.coverage.mutation.MutationSystemTest.testStrongMutationPropagationExampleWithoutArchive
- [ ] org.evosuite.coverage.mutation.MutationSystemTest.testStrongMutationSimpleExampleWithoutArchive
- [ ] org.evosuite.determinism.BaseDeterminismSystemTest.testBase
- [ ] org.evosuite.determinism.BaseDeterminismSystemTest.testDSE
- [ ] org.evosuite.determinism.BaseDeterminismSystemTest.testLS
- [ ] org.evosuite.ga.metaheuristics.MIOSystemTest.testArchiveSampling
- [ ] org.evosuite.ga.metaheuristics.MIOSystemTest.testIntegration
- [ ] org.evosuite.ga.metaheuristics.MIOSystemTest.testRandomSampling
- [ ] org.evosuite.ga.metaheuristics.NSGAIISystemTest.testIntegration
- [ ] org.evosuite.ga.metaheuristics.SPEA2SystemTest.minimalSpacing
- [ ] org.evosuite.ga.metaheuristics.SPEA2SystemTest.nonMinimalSpacing
- [ ] org.evosuite.ga.problems.multiobjective.FONIntTest.testFON
- [ ] org.evosuite.ga.problems.multiobjective.KURIntTest.testKUR
- [ ] org.evosuite.ga.problems.multiobjective.POLIntTest.testPOL
- [ ] org.evosuite.ga.problems.multiobjective.SCH2IntTest.testSCH2
- [ ] org.evosuite.ga.problems.multiobjective.SCHIntTest.testSCH
- [ ] org.evosuite.instrumentation.error.ArrayInstrumentationSystemTest.testArrayAccessWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayInstrumentationSystemTest.testArrayAccessWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayInstrumentationSystemTest.testArrayCreationWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayInstrumentationSystemTest.testArrayCreationWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAccessWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAccessWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAddAllWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAddAllWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAddWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListAddWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListIteratorWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListIteratorWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListRemoveWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListRemoveWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListSetWithErrorBranches
- [ ] org.evosuite.instrumentation.error.ArrayListInstrumentationSystemTest.testArrayListSetWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.CastInstrumentationSystemTest.testCastWithErrorBranches
- [ ] org.evosuite.instrumentation.error.CastInstrumentationSystemTest.testCastWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeElementWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeElementWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeGetFirstWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeGetFirstWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequePopWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequePopWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeRemoveFirstWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeRemoveFirstWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeRemoveWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DequeInstrumentationSystemTest.testDequeRemoveWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testDoubleDivisionWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testDoubleDivisionWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testIntDivisionWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testIntDivisionWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testLongDivisionWithErrorBranches
- [ ] org.evosuite.instrumentation.error.DivisionByZeroInstrumentationSystemTest.testLongDivisionWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.LinkedListInstrumentationSystemTest.testLinkedListIndexWithErrorBranches
- [ ] org.evosuite.instrumentation.error.LinkedListInstrumentationSystemTest.testLinkedListIndexWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.LinkedListInstrumentationSystemTest.testLinkedListWithErrorBranches
- [ ] org.evosuite.instrumentation.error.LinkedListInstrumentationSystemTest.testLinkedListWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.NullPointerInstrumentationSystemTest.testFieldWithErrorBranches
- [ ] org.evosuite.instrumentation.error.NullPointerInstrumentationSystemTest.testFieldWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.NullPointerInstrumentationSystemTest.testMethodCallWithErrorBranches
- [ ] org.evosuite.instrumentation.error.NullPointerInstrumentationSystemTest.testMethodCallWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntAddOverflowWithErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntAddOverflowWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntDivOverflowWithErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntDivOverflowWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntMulOverflowWithErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntSubOverflowWithErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testIntSubOverflowWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.OverflowInstrumentationSystemTest.testMulDivOverflowWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.QueueInstrumentationSystemTest.testQueueElementOperationWithErrorBranches
- [ ] org.evosuite.instrumentation.error.QueueInstrumentationSystemTest.testQueueElementOperationWithOutErrorBranches
- [ ] org.evosuite.instrumentation.error.QueueInstrumentationSystemTest.testQueueRemoveOperationWithErrorBranches
- [ ] org.evosuite.instrumentation.error.QueueInstrumentationSystemTest.testQueueRemoveOperationWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.StackInstrumentationSystemTest.testStackPeekOperationWithErrorBranches
- [ ] org.evosuite.instrumentation.error.StackInstrumentationSystemTest.testStackPeekOperationWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.StackInstrumentationSystemTest.testStackPopOperationWithErrorBranches
- [ ] org.evosuite.instrumentation.error.StackInstrumentationSystemTest.testStackPopOperationWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.VectorInstrumentationSystemTest.testVectorIndexWithErrorBranches
- [ ] org.evosuite.instrumentation.error.VectorInstrumentationSystemTest.testVectorIndexWithoutErrorBranches
- [ ] org.evosuite.instrumentation.error.VectorInstrumentationSystemTest.testVectorWithErrorBranches
- [ ] org.evosuite.instrumentation.error.VectorInstrumentationSystemTest.testVectorWithoutErrorBranches
- [ ] org.evosuite.jee.DBSystemTest.testSimpleDBInteraction
- [ ] org.evosuite.jee.DBSystemTest.testSimpleDBInteraction
- [ ] org.evosuite.jee.DBSystemTest.testSimpleDBWrite
- [ ] org.evosuite.jee.DBSystemTest.testSimpleDBWrite
- [ ] org.evosuite.jee.InjectionSystemTest.testCombination
- [ ] org.evosuite.jee.InjectionSystemTest.testCombination
- [ ] org.evosuite.jee.InjectionSystemTest.testCombination3
- [ ] org.evosuite.jee.InjectionSystemTest.testCombination3
- [ ] org.evosuite.jee.InjectionSystemTest.testEntityManager
- [ ] org.evosuite.jee.InjectionSystemTest.testEntityManager
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionAndPostConstruct
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionAndPostConstruct
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionInInputParameter
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionInInputParameter
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionSimpleInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionSimpleInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionSourceForItself
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionSourceForItself
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionTrivialInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionTrivialInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionWithInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionWithInheritance
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionWithSimpleMethods
- [ ] org.evosuite.jee.InjectionSystemTest.testInjectionWithSimpleMethods
- [ ] org.evosuite.jee.InjectionSystemTest.testMultipleDefaultInjections
- [ ] org.evosuite.jee.InjectionSystemTest.testMultipleDefaultInjections
- [ ] org.evosuite.jee.InjectionSystemTest.testPostConstructor
- [ ] org.evosuite.jee.InjectionSystemTest.testPostConstructor
- [ ] org.evosuite.jee.WildflySystemTest.testTransactionServlet
- [ ] org.evosuite.jee.WildflySystemTest.testTransactionServlet
- [ ] org.evosuite.junit.CoverageAnalysisCharSequenceSystemTest.test
- [ ] org.evosuite.junit.CoverageAnalysisFinalClassSystemTest.test
- [ ] org.evosuite.junit.CoverageAnalysisLocaleSystemTest.test
- [ ] org.evosuite.junit.CoverageAnalysisOfClassSystemTest.testMeasureCoverageOfCarvedTests
- [ ] org.evosuite.junit.CoverageAnalysisOfClassSystemTest.testOneClassMoreThanOneCriterion
- [ ] org.evosuite.junit.CoverageAnalysisOfClassSystemTest.testOneClassOneCriterion
- [ ] org.evosuite.junit.CoverageAnalysisOfEvoSuiteTestSuiteSystemTest.testOneFitnessFunction
- [ ] org.evosuite.junit.CoverageAnalysisOfProjectSystemTest.testMoreThanOneClassMoreThanOneCriterion
- [ ] org.evosuite.junit.CoverageAnalysisOfProjectSystemTest.testMoreThanOneClassOneCriterion
- [ ] org.evosuite.junit.CoverageAnalysisStringInstrumentationSystemTest.testCreateBigInteger
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testAmbiguityCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testBranchCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testCBranchCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testLineCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testOnlyBranchCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testOnlyLineCoverage
- [ ] org.evosuite.junit.CoverageAnalysisSystemTest.testRhoCoverage
- [ ] org.evosuite.junit.CoverageAnalysisWithRefectionSystemTest.testBindFilteredEventsToMethod
- [ ] org.evosuite.junit.CoverageAnalysisWithRefectionSystemTest.testGetAllInterfaces
- [ ] org.evosuite.junit.CoverageAnalysisWithRefectionSystemTest.testHierarchyIncludingInterfaces
- [ ] org.evosuite.localsearch.Issre13SystemTest.testDSE
- [ ] org.evosuite.localsearch.Issre13SystemTest.testOnSpecificTest
- [ ] org.evosuite.localsearch.LocalSearchSystemTest.testStringLocalSearch
- [ ] org.evosuite.runtime.sandbox.GeneratedFilesEvenWithSandboxSystemTest.testCreateInATryCatch
- [ ] org.evosuite.runtime.sandbox.ReadWriteSystemPropertiesSystemTest.testNoReplace
- [ ] org.evosuite.seeding.factories.BIandRITestSuiteChromosomeFactorySystemTest.testNotSeed
- [ ] org.evosuite.seeding.factories.RandomIndividualTestSuiteChromosomeFactorySystemTest.testNotSeed
- [ ] org.evosuite.statistics.SearchStatisticsTest.test_setOutputVariable
- [ ] org.evosuite.TargetMethodSystemTest.testTargetMethodWithTRYCATCH
- [ ] org.evosuite.testcarver.CarverSystemTest.testJodaTestScaledDurationField
- [ ] org.evosuite.testcarver.CarverSystemTest.testPublicStaticField
- [ ] org.evosuite.testcase.ChangeMutationSystemTest.testTwoIntsLineCoverage
- [ ] org.evosuite.testcase.JUnitTestCarvedChromosomeFactorySystemTest.testJavaAgent

**Comment by VoglSebastian** [comment]
I had a brief look on the integration tests.

It looks like, that the main problem of the failing integration tests occurs during org.evosuite.runtime.System.\<clinit\> in line:

https://github.com/VoglSebastian/evosuite/blob/7d96730439f9da12d0e30cf124fabd42e4614614/runtime/src/main/java/org/evosuite/runtime/System.java#L59

java.lang.System.getProperties() causes the SecurityManager to call org.evosuite.runtime.System.isSystemProperty(String). 

At this point org.evosuite.runtime.System.systemProperties is not initialized and throws a NullPointerException.

I don't know what part of the refactoring caused this to happen, but it looks like moving the initialization of systemProperties to the start of \<clinit\> would solve this.

I tried this in branch FixIntegrationTests (79ac4ec) and it works on my machine for the first 5 system tests (I have not run the others yet).

Can anyone confirm, that this fix works in general?
Was there a reason why the systemProperties were initialized after the defaultProperties?

**Comment by schweikl** [comment]
Hi,

we have a Jenkins server (I sent you a PM) that periodically polls the `selfType` branch for changes and re-executes the integration tests if necessary. Your changes look good to me and (as you mentioned) they seem to work for the first 5 system tests.  So, I think we could just give it a chance and simply merge your changes into the `selfType` branch and see what happens :grinning: If it fixes the issues, then it's all good, and if not, we can at least use the output from Jenkins to further investigate the issue.
