### ISSUE TITLE
Continue implementation of TestSuiteAdapter

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#5]
### Context
`TestSuiteAdapter` is intended as a compatibility layer to bridge the gap between `GeneticAlgorithm<TestChromosome>` and `GeneticAlgorithm<TestSuiteChromosome>`. The main beneficiaries of this are the algorithms `MOSA`, `MIO` and `LIPS`. Up until now, many of the methods in `TestSuiteAdapter` are still left unimplemented, simply throwing an `UnsupportedOperationException("not implemented")` when being invoked. While all the methods relevant for `MOSA` should already be implemented, it is unclear whether this is also the case for `MIO` and `LIPS`.

### Expected result
Please check if an implementation of the following methods is necessary for `MOSA`, `MIO` or `LIPS` and give an appropriate implementation if possible (just tick the boxes once you're done):
- [x] `void evolve()` *
- [x] `void initializePopulation()` *
- [x] `void notifyMutation(TestSuiteChromosome chromosome)` *
- [x] `void notifyEvaluation(TestSuiteChromosome chromosome)` *
- [x] `boolean shouldApplyLocalSearch()`
- [x] `void disableFirstSecondaryCriterion()` *
- [x] `void enableFirstSecondaryCriterion()` *
- [x] `void updateSecondaryCriterion(int starvationCounter)` *
- [x] `void applyLocalSearch()`
- [x] `void updateProbability(boolean improvement)` *
- [x] `void generateInitialPopulation(int populationSize)` *
- [x] `void starveToLimit(int limit)` *
- [x] `void starveRandomly(int limit)` *
- [x] `void starveByFitness(int limit)` *
- [x] `void generateRandomPopulation(int populationSize)` *
- [x] `void clearPopulation()` *
- [x] `void addFitnessFunction(final FitnessFunction< TestSuiteChromosome> function)`
- [x] `FitnessFunction<TestSuiteChromosome> getFitnessFunction()` *
- [x] `int getNumberOfFitnessFunctions()` *
- [x] `SelectionFunction<TestSuiteChromosome> getSelectionFunction()` *
- [x] `RankingFunction<TestSuiteChromosome> getRankingFunction()` *
- [x] `void setRankingFunction(RankingFunction<TestSuiteChromosome> function)` *
- [x] `void setBloatControl(BloatControlFunction<TestSuiteChromosome> bcf)` *
- [x] `void addBloatControl(BloatControlFunction<TestSuiteChromosome> bloatControl)`
- [x] `boolean isTooLong(TestSuiteChromosome chromosome)` 
- [x] `void calculateFitness()`
- [x] `void calculateFitness(TestSuiteChromosome c)`
- [x] `void calculateFitnessAndSortPopulation()` *
- [x] `int getPopulationSize()` *
- [x] `List<TestSuiteChromosome> elitism()` *
- [x] `List<TestSuiteChromosome> randomism()` *
- [x] `void updateFitnessFunctionsAndValues()` *
- [x] `void writeIndividuals(List<TestSuiteChromosome> individuals)` *
- [x] `void removeListener(SearchListener<TestSuiteChromosome> listener)` 
- [x] `void sortPopulation()` *
- [x] `List<TestSuiteChromosome> getPopulation()`
- [x] `boolean isNextPopulationFull(List<TestSuiteChromosome> nextGeneration)` 
- [x] `boolean isFinished()`
- [x] `void setStoppingConditionLimit(int value)` *
- [x] `void updateBestIndividualFromArchive()` *
- [x] `boolean isBetterOrEqual(TestSuiteChromosome chromosome1, TestSuiteChromosome chromosome2)`
- [x] `void printBudget()` *
- [x] `String getBudgetString()` *
- [x] `double progress()` *

To this, one might simply run EvoSuite with the appropriate command line flags to enable `MOSA`, `MIO` and `LIPS` and observe whether EvoSuite currently crashes with an `UnsupportedOperationException`. If this is the case, one can simply look at the stack trace and identify the method that caused the exception. This method is one that still needs to be implemented.

### Contributing
Please push your changes to the branch [`5-continue-implementation-of-testsuite-adapter`](https://github.com/VoglSebastian/evosuite/tree/5-continue-implementation-of-testsuite-adapter)

**Comment by schweikl** [comment]
One more thing: when adapting – let's say – a `SearchListener` one has to carefully check whether the **state** of the adapted `SearchListener` needs to be copied as well. It might not be sufficient to simply create a new `SearchListener` of the appropriate type! Of course, this applies to **all** the methods listed above, not just the ones using a `SearchListener`. For example, `TestSuiteAdapter` already contains a `private static class TestSuiteFitnessFunctionWrapper` that adapts `TestSuiteFitnessFunction`s. To this, it for example checks whether the wrapped function is a maximizing fitness function or not.

**Comment by schweikl** [comment]
`void addBloatControl(BloatControlFunction<TestSuiteChromosome> bloatControl)` is now a requirement to closing #16 and merging #18

**Comment by schweikl** [comment]
> `void addBloatControl(BloatControlFunction<TestSuiteChromosome> bloatControl)` is now a requirement to closing #16 and merging #18

Fixed by #21

**Comment by VoglSebastian** [comment]
Is the TestSuiteAdapter supposed to prevent EvoSuite from calling methods on the algorithm, if that method does not make sense to call?

Or should every adaptee check if it makes sense to call a method and the adapter just redirects the calls (after conversion from TestSuiteChromosome to Test Chromosome)?

**Comment by VoglSebastian** [comment]
Currently TestSuiteAdapter::addListener(SearchListener<TestSuiteChromosome>) add listener to the Adapter.

Is that intended? Since the Adapter does not mutate/evaluate and has iterations itself, i think the listeners are only notified about the start and end of the search.

I don't believe this is the intended functionality.

We should either:

1. Transform the search listener and add it to the adaptee algorithm.
2. Add an search listener to the adaptee algorithm, when the adapter is initialized. The added listener notifies the adapter, who then notify itselfs search listeners

Or am i missing something?

**Comment by VoglSebastian** [comment]
> Currently TestSuiteAdapter::addListener(SearchListener) add listener to the Adapter.
> 
> Is that intended? Since the Adapter does not mutate/evaluate and has iterations itself, i think the listeners are only notified about the start and end of the search.
> 
> I don't believe this is the intended functionality.
> 
> We should either:
> 
> 1. Transform the search listener and add it to the adaptee algorithm.
> 2. Add an search listener to the adaptee algorithm, when the adapter is initialized. The added listener notifies the adapter, who then notify itselfs search listeners
> 
> Or am i missing something?

I just saw, that a variant of 2 is already implemented, but not using the searchListener Interfaces. I would suggest we introduce a new SearchListener, that is added to the adaptee algorithm instead of overwriting every notify method of every adaptee algorithm to additionally notify the Adapter

**Comment by VoglSebastian** [comment]
I have marked all functions that would be finished with PR #37 with "*"

**Comment by schweikl** [comment]
As it appears some integration tests still fail (#32) due to missing or incomplete implementations in `TestSuiteAdapter`. Exmaple:
```
java.lang.IllegalArgumentException: cannot adapt stopping condition: ZeroFitness :           9,223,372,036,854,775,807 / 0
	at org.evosuite.ga.metaheuristics.TestSuiteAdapter.mapStoppingCondition(TestSuiteAdapter.java:542) ~[classes/:na]
	at org.evosuite.ga.metaheuristics.TestSuiteAdapter.addStoppingCondition(TestSuiteAdapter.java:503) ~[classes/:na]
```

EDIT: I just fixed this particular problem in 91cad25. The fix was trivial. Let's hope it's that simple for all other failing tests as well :sweat_smile:

**Comment by VoglSebastian** [comment]
What behaviour is expected for isBetterOrEqual?

1. Pareto dominance? (Assuming each Chromosome contains a population)
2. just sum the fitness values for all fitness functions?
3. Assume, that the TestSuiteChromosomes will contain only 1 TestCase and let the algorithm handle them. (If more than 1 test case is contained -> throw Exception)?

I just had a brief look at the current Implementation:
isBetterOrEqual is not overwritten by any subclasses. 
The default Implementation uses Chromosome::compareTo, which just sums up all fitnessValues.
(Similar to 2.). I think, that this is not a good implementation Algorithms on TestCase level, since the fitness values may not be normalized.

**Comment by schweikl** [comment]
That's a good question, to which I don't know an answer atm. I am unsure if `isBetterOrEqual` can be redefined in a meaningful way for the `TestSuiteAdapter` :thinking:

**Comment by VoglSebastian** [comment]
6ce07e7

has implemented removeListener.

We discussed, that we won't implement functionality for the remaining unimplemented functions.

Maybe we have to implement some more conversion from test suite to test case level.

But i think we can close this issue?

**Comment by schweikl** [comment]
Yep, I think we can close this now. Everything that needs to be implemented to make EvoSuite and its integration tests work has been implemented. And as you pointed out, if we really find the need to implement some more conversions from test suites to test cases we can always do this on demand. So I think we're good to go :+1:
