### ISSUE TITLE
How To Convert TestChromosomes into TestSuiteChromosome?

### ISSUE THREAD

**Issue by schweikl** [VoglSebastian/evosuite#9]
### Context
`MOSA`, `MIO` and `LIPS` all operate on `TestChromosomes` but ultimately they must return a `TestSuiteChromosome` as search result. In principle, the conversion should be straight-forward:
1. Create a new `TestSuiteChromosome`
2. Add as many `TestChromosomes` as necessary using `TestSuiteChromosome::addTest`
Yet, it seems that all three of the mentioned algorithms handle the conversion of `TestChromosomes` into a `TestSuiteChromosome` differently. What is the proper way to do it?

Related Issues: #5 #6 

### Additional info

- There seems to be a semantic difference between `getBestIndividual()` and `getBestIndividuals()`. The former is used by `ProgressMonitor` after every generation, while the latter represents the actual result of the algorithm after the search terminated.
- `MOSA` calls `Archive.getArchiveInstance().mergeArchiveAndSolution(new TestSuiteChromosome());` to create the `TestSuiteChromosome`. If this test suite is empty, it adds the test cases given by `getAlgorithm().getBestIndividuals()`.
 https://github.com/VoglSebastian/evosuite/blob/4d04214627f91f2f8baa8b39bcc46d315745793e/client/src/main/java/org/evosuite/ga/metaheuristics/mosa/MOSATestSuiteAdapter.java#L35
- `LIPS` creates a `new TestSuiteChromosome()` and adds all test cases given by `getAlgorithm().getFinalTestSuite()`, but in addition it also computes "overall fitness and coverage" in a different way than `MOSA` and `MIO`.
https://github.com/VoglSebastian/evosuite/blob/4d04214627f91f2f8baa8b39bcc46d315745793e/client/src/main/java/org/evosuite/ga/metaheuristics/LIPSTestSuiteAdapter.java#L42
- `MIO` creates a `new TestSuiteChromosome()` and adds all test cases given by `Archive.getArchiveInstance().getSolutions()`. Then it computes overall fitness and coverage the same way as `MOSA`.
 https://github.com/VoglSebastian/evosuite/blob/4d04214627f91f2f8baa8b39bcc46d315745793e/client/src/main/java/org/evosuite/ga/metaheuristics/MIOTestSuiteAdapter.java#L20

**Comment by VoglSebastian** [comment]
Hi, i have added a Collector for TestChromosomes to TestSuiteChromosomes (TestChromosome.TestChromosomeCollector), which can be used by:

listOfTestChromosomes.stream().collect(TestChromosome.toTestSuiteCollector)

The collector does not check if any duplicate TestChromosomes are added. (Like MOSA does)
Is this intended?

**Comment by schweikl** [comment]
Hi, I guess the `Collector` is fine. But does that close our issue? My question was not so much about the "mechanics" of the conversion but rather whether the conversion must be done differently depending on the algorithm that is used :sweat_smile:

**Comment by schweikl** [comment]
Won't fix – the resolution to #10 already provides a sane way to convert from `TestChromosome` to `TestSuiteChromosome`. The special handling of the conversion in `MIO`, `LIPS` and `MOSA` is caused by other factors.
